export const countries = [
    { value: "AFG", label: "Afeganistão" },
    { value: "ZAF", label: "África do Sul" },
    { value: "ALB", label: "Albânia" },
    { value: "DEU", label: "Alemanha" },
    { value: "AND", label: "Andorra" },
    { value: "AGO", label: "Angola" },
    { value: "AIA", label: "Anguilla" },
    { value: "ATA", label: "Antártida" },
    { value: "ATG", label: "Antígua e Barbuda" },
    { value: "SAU", label: "Arábia Saudita" },
    { value: "DZA", label: "Argélia" },
    { value: "ARG", label: "Argentina" },
    { value: "ARM", label: "Armênia" },
    { value: "IOT", label: "Arquipélago de Chagos" },
    { value: "ABW", label: "Aruba" },
    { value: "AUS", label: "Austrália" },
    { value: "AUT", label: "Áustria" },
    { value: "AZE", label: "Azerbaijão" },
    { value: "BHS", label: "Bahamas" },
    { value: "BHR", label: "Bahrein" },
    { value: "BGD", label: "Bangladesh" },
    { value: "BRB", label: "Barbados" },
    { value: "BEL", label: "Bélgica" },
    { value: "BLZ", label: "Belize" },
    { value: "BEN", label: "Benin" },
    { value: "BMU", label: "Bermudas" },
    { value: "BLR", label: "Bielorrússia" },
    { value: "BOL", label: "Bolívia" },
    { value: "BIH", label: "Bósnia e Herzegovina" },
    { value: "BWA", label: "Botsuana" },
    { value: "BRA", label: "Brasil" },
    { value: "BRN", label: "Brunei" },
    { value: "BGR", label: "Bulgária" },
    { value: "BFA", label: "Burquina Faso" },
    { value: "BDI", label: "Burundi" },
    { value: "BTN", label: "Butão" },
    { value: "CPV", label: "Cabo Verde" },
    { value: "KHM", label: "Camboja" },
    { value: "CMR", label: "Cameroun" },
    { value: "CAN", label: "Canadá" },
    { value: "QAT", label: "Catar" },
    { value: "KAZ", label: "Cazaquistão" },
    { value: "TCD", label: "Chade" },
    { value: "CHL", label: "Chile" },
    { value: "CHN", label: "China continental" },
    { value: "CYP", label: "Chipre" },
    { value: "VAT", label: "Cidade do Vaticano" },
    { value: "COL", label: "Colômbia" },
    { value: "COM", label: "Comores" },
    { value: "KOR", label: "Coreia do Sul" },
    { value: "CIV", label: "Costa do Marfim" },
    { value: "CRI", label: "Costa Rica" },
    { value: "HRV", label: "Croácia" },
    { value: "CUW", label: "Curaçau" },
    { value: "DNK", label: "Dinamarca" },
    { value: "DJI", label: "Djibuti" },
    { value: "DMA", label: "Dominica" },
    { value: "EGY", label: "Egito" },
    { value: "SLV", label: "El Salvador" },
    { value: "ARE", label: "Emirados Árabes Unidos" },
    { value: "ECU", label: "Equador" },
    { value: "ERI", label: "Eritreia" },
    { value: "SVK", label: "Eslováquia" },
    { value: "SVN", label: "Eslovênia" },
    { value: "ESP", label: "Espanha" },
    { value: "SWZ", label: "Essuatíni" },
    { value: "USA", label: "Estados Unidos" },
    { value: "EST", label: "Estônia" },
    { value: "ETH", label: "Etiópia" },
    { value: "FJI", label: "Fiji" },
    { value: "PHL", label: "Filipinas" },
    { value: "FIN", label: "Finlândia" },
    { value: "FRA", label: "França" },
    { value: "GAB", label: "Gabão" },
    { value: "GMB", label: "Gâmbia" },
    { value: "GHA", label: "Gana" },
    { value: "GEO", label: "Geórgia" },
    { value: "GIB", label: "Gibraltar" },
    { value: "GRD", label: "Granada" },
    { value: "GRC", label: "Grécia" },
    { value: "GRL", label: "Groelândia" },
    { value: "GLP", label: "Guadalupe" },
    { value: "GUM", label: "Guam" },
    { value: "GTM", label: "Guatemala" },
    { value: "GGY", label: "Guernsey" },
    { value: "GUY", label: "Guiana" },
    { value: "GUF", label: "Guiana Francesa" },
    { value: "GIN", label: "Guiné" },
    { value: "GNB", label: "Guiné-Bissau" },
    { value: "GNQ", label: "Guiné Equatorial" },
    { value: "HTI", label: "Haiti" },
    { value: "NLD", label: "Holanda" },
    { value: "HND", label: "Honduras" },
    { value: "HKG", label: "Hong Kong" },
    { value: "HUN", label: "Hungria" },
    { value: "YEM", label: "Iémen" },
    { value: "BVT", label: "Ilha Bouvet" },
    { value: "CXR", label: "Ilha Christmas" },
    { value: "IMN", label: "Ilha de Man" },
    { value: "NFK", label: "Ilha Norfolk" },
    { value: "ALA", label: "Ilhas Åland" },
    { value: "CYM", label: "Ilhas Cayman" },
    { value: "CCK", label: "Ilhas Cocos (Keeling)" },
    { value: "COK", label: "Ilhas Cook" },
    { value: "FRO", label: "Ilhas Faroe" },
    { value: "SGS", label: "Ilhas Geórgia do Sul e Sandwich do Sul" },
    { value: "HMD", label: "Ilhas Heard e McDonald" },
    { value: "FLK", label: "Ilhas Malvinas" },
    { value: "MNP", label: "Ilhas Marianas do Norte" },
    { value: "MHL", label: "Ilhas Marshall" },
    { value: "UMI", label: "Ilhas Menores Distantes dos Estados Unidos" },
    { value: "PCN", label: "Ilhas Pitcairn" },
    { value: "SLB", label: "Ilhas Salomão" },
    { value: "TCA", label: "Ilhas Turks e Caicos" },
    { value: "VIR", label: "Ilhas Virgens Americanas" },
    { value: "VGB", label: "Ilhas Virgens Britânicas" },
    { value: "IND", label: "Índia" },
    { value: "IDN", label: "Indonésia" },
    { value: "IRQ", label: "Iraque" },
    { value: "IRL", label: "Irlanda" },
    { value: "ISL", label: "Islândia" },
    { value: "ISR", label: "Israel" },
    { value: "ITA", label: "Itália" },
    { value: "JAM", label: "Jamaica" },
    { value: "JPN", label: "Japão" },
    { value: "JEY", label: "Jersey" },
    { value: "JOR", label: "Jordânia" },
    { value: "KEN", label: "Quênia" },
    { value: "KIR", label: "Kiribati" },
    { value: "KWT", label: "Kuwait" },
    { value: "KGZ", label: "Quirguistão" },
    { value: "LAO", label: "Laos" },
    { value: "LVA", label: "Letônia" },
    { value: "LBN", label: "Líbano" },
    { value: "LSO", label: "Lesoto" },
    { value: "LBR", label: "Libéria" },
    { value: "LBY", label: "Líbia" },
    { value: "LIE", label: "Liechtenstein" },
    { value: "LTU", label: "Lituânia" },
    { value: "LUX", label: "Luxemburgo" },
    { value: "MKD", label: "Macedônia do Norte" },
    { value: "MDG", label: "Madagáscar" },
    { value: "MWI", label: "Malawi" },
    { value: "MYS", label: "Malásia" },
    { value: "MDV", label: "Maldivas" },
    { value: "MLI", label: "Mali" },
    { value: "MLT", label: "Malta" },
    { value: "MAR", label: "Marrocos" },
    { value: "MTQ", label: "Martinica" },
    { value: "MUS", label: "Maurício" },
    { value: "MRT", label: "Mauritânia" },
    { value: "MYT", label: "Mayotte" },
    { value: "MEX", label: "México" },
    { value: "MMR", label: "Mianmar" },
    { value: "FSM", label: "Micronésia" },
    { value: "MOZ", label: "Moçambique" },
    { value: "MDA", label: "Moldávia" },
    { value: "MCO", label: "Mônaco" },
    { value: "MNG", label: "Mongólia" },
    { value: "MNE", label: "Montenegro" },
    { value: "MSR", label: "Montserrat" },
    { value: "NAM", label: "Namíbia" },
    { value: "NRU", label: "Nauru" },
    { value: "NPL", label: "Nepal" },
    { value: "NIC", label: "Nicarágua" },
    { value: "NER", label: "Níger" },
    { value: "NGA", label: "Nigéria" },
    { value: "NIU", label: "Niue" },
    { value: "NOR", label: "Noruega" },
    { value: "NCL", label: "Nova Caledônia" },
    { value: "NZL", label: "Nova Zelândia" },
    { value: "OMN", label: "Omã" },
    { value: "BES", label: "Países Baixos Caribenhos" },
    { value: "PLW", label: "Palau" },
    { value: "PAN", label: "Panamá" },
    { value: "PNG", label: "Papua-Nova Guiné" },
    { value: "PAK", label: "Paquistão" },
    { value: "PRY", label: "Paraguai" },
    { value: "PER", label: "Peru" },
    { value: "PYF", label: "Polinésia Francesa" },
    { value: "POL", label: "Polônia" },
    { value: "PRI", label: "Porto Rico" },
    { value: "PRT", label: "Portugal" },
    { value: "GBR", label: "Reino Unido" },
    { value: "CAF", label: "República Centro-Africana" },
    { value: "COD", label: "República Democrática do Congo" },
    { value: "COG", label: "República do Congo" },
    { value: "DOM", label: "República Dominicana" },
    { value: "REU", label: "Reunião" },
    { value: "ROU", label: "Romênia" },
    { value: "RWA", label: "Ruanda" },
    { value: "RUS", label: "Rússia" },
    { value: "ESH", label: "Saara Ocidental" },
    { value: "MAF", label: "Saint-Martin" },
    { value: "WSM", label: "Samoa" },
    { value: "ASM", label: "Samoa Americana" },
    { value: "SMR", label: "San Marino" },
    { value: "SHN", label: "Santa Helena" },
    { value: "LCA", label: "Santa Lúcia" },
    { value: "BLM", label: "São Bartolomeu" },
    { value: "KNA", label: "São Cristóvão e Névis" },
    { value: "SPM", label: "São Pedro e Miquelão" },
    { value: "STP", label: "São Tomé e Príncipe" },
    { value: "VCT", label: "São Vicente e Granadinas" },
    { value: "SYC", label: "Seicheles" },
    { value: "SEN", label: "Senegal" },
    { value: "SLE", label: "Serra Leoa" },
    { value: "SRB", label: "Sérvia" },
    { value: "SGP", label: "Singapura" },
    { value: "SXM", label: "Sint Maarten" },
    { value: "SOM", label: "Somália" },
    { value: "LKA", label: "Sri Lanka" },
    { value: "SDN", label: "Sudão" },
    { value: "SSD", label: "Sudão do Sul" },
    { value: "SWE", label: "Suécia" },
    { value: "CHE", label: "Suíça" },
    { value: "SUR", label: "Suriname" },
    { value: "SJM", label: "Svalbard e Jan Mayen" },
    { value: "TJK", label: "Tadjiquistão" },
    { value: "THA", label: "Tailândia" },
    { value: "TWN", label: "Taiwan" },
    { value: "TZA", label: "Tanzânia" },
    { value: "CZE", label: "Tchéquia" },
    { value: "ATF", label: "Territórios Franceses do Sul" },
    { value: "PSE", label: "Territórios Palestinos" },
    { value: "TLS", label: "Timor-Leste" },
    { value: "TGO", label: "Togo" },
    { value: "TKL", label: "Tokelau" },
    { value: "TON", label: "Tonga" },
    { value: "TTO", label: "Trinidad e Tobago" },
    { value: "TUN", label: "Tunísia" },
    { value: "TKM", label: "Turcomenistão" },
    { value: "TUR", label: "Turquia" },
    { value: "TUV", label: "Tuvalu" },
    { value: "UKR", label: "Ucrânia" },
    { value: "UGA", label: "Uganda" },
    { value: "URY", label: "Uruguai" },
    { value: "UZB", label: "Uzbequistão" },
    { value: "VUT", label: "Vanuatu" },
    { value: "VEN", label: "Venezuela" },
    { value: "VNM", label: "Vietnã" },
    { value: "WLF", label: "Wallis e Futuna" },
    { value: "ZMB", label: "Zâmbia" },
    { value: "ZWE", label: "Zimbábue" }
  ];
  